import type { Body, Condition, Drivetrain, Fuel, ServiceHistory } from "../src/lib/types";

/**
 * Demo-Fahrzeugbestand für die Entwicklungsumgebung. Preise in CHF.
 * Erstzulassungen sind relativ zum Stichtag 2026-09 gewählt.
 */
export interface SeedVehicle {
  id: string;
  make: string;
  model: string;
  trim: string;
  year: number;
  firstRegistration: string;
  mileageKm: number;
  fuel: Fuel;
  body: Body;
  drivetrain: Drivetrain;
  powerPs: number;
  listPriceNew: number;
  condition: Condition;
  color: string;
  rangeKm?: number;
  batterySoh?: number;
  features: string[];
  notes?: string;
  defects?: string[];
  serviceHistory: ServiceHistory;
  previousOwners: number;
  accidentFree: boolean;
  mfkUntil?: string;
}

export interface SeedListing {
  id: string;
  vehicleId: string;
  ownerId: string;
  createdAt: string;
  wish: {
    makes: string[];
    bodies: Body[];
    fuels: Fuel[];
    minYear?: number;
    maxMileageKm?: number;
    maxCashOut?: number;
    notes?: string;
  };
  askPremium?: number;
  views: number;
}

export const seedVehicles: SeedVehicle[] = [
  {
    id: "v-001",
    make: "Polestar",
    model: "4",
    trim: "Long Range Dual Motor",
    year: 2024,
    firstRegistration: "2024-06-14",
    mileageKm: 27_400,
    fuel: "elektro",
    body: "suv",
    drivetrain: "allrad",
    powerPs: 544,
    listPriceNew: 84_900,
    condition: "sehr gut",
    color: "Space",
    rangeKm: 580,
    batterySoh: 96,
    features: ["Panoramadach", "Harman Kardon", "Pilot Assist", "Wärmepumpe", "360°-Kamera", "Winterräder"],
    notes:
      "Erstbesitz, immer garagiert, Nichtraucher. Performance-Paket mit Öhlins-Dämpfern nachgerüstet. Winterräder auf Original-Alu dabei.",
    serviceHistory: "lückenlos scheckheft",
    previousOwners: 1,
    accidentFree: true,
    mfkUntil: "2027-06-14",
  },
  {
    id: "v-019",
    make: "Skoda",
    model: "Octavia Combi",
    trim: "2.0 TDI Style DSG",
    year: 2021,
    firstRegistration: "2021-03-02",
    mileageKm: 96_800,
    fuel: "diesel",
    body: "kombi",
    drivetrain: "front",
    powerPs: 150,
    listPriceNew: 44_200,
    condition: "gut",
    color: "Graphitgrau",
    features: ["Anhängerkupplung", "Matrix-LED", "Standheizung", "Winterräder"],
    notes: "Zuverlässiger Zweitwagen, Anhängerkupplung für den Pferdeanhänger.",
    serviceHistory: "lückenlos scheckheft",
    previousOwners: 1,
    accidentFree: true,
    mfkUntil: "2027-03-02",
  },

  {
    id: "v-002",
    make: "Zeekr",
    model: "7X",
    trim: "Privilege AWD",
    year: 2025,
    firstRegistration: "2025-04-08",
    mileageKm: 14_900,
    fuel: "elektro",
    body: "suv",
    drivetrain: "allrad",
    powerPs: 646,
    listPriceNew: 78_400,
    condition: "neuwertig",
    color: "Polar Weiss",
    rangeKm: 480,
    batterySoh: 98,
    features: ["Panoramadach", "Luftfederung", "Massagesitze", "Head-up-Display", "360°-Kamera", "Wärmepumpe"],
    notes:
      "Direktimport, in der Schweiz verzollt und ab MFK. 800-V-Architektur, lädt an HPC in 13 Minuten von 10 auf 80 %. Ich suche etwas mit mehr Reichweite für Langstrecke.",
    serviceHistory: "lückenlos scheckheft",
    previousOwners: 1,
    accidentFree: true,
    mfkUntil: "2029-04-08",
  },
  {
    id: "v-003",
    make: "Zeekr",
    model: "7X",
    trim: "Core RWD",
    year: 2025,
    firstRegistration: "2025-09-19",
    mileageKm: 21_300,
    fuel: "elektro",
    body: "suv",
    drivetrain: "heck",
    powerPs: 421,
    listPriceNew: 64_900,
    condition: "sehr gut",
    color: "Mineral Grau",
    rangeKm: 445,
    batterySoh: 97,
    features: ["Panoramadach", "Wärmepumpe", "360°-Kamera", "Winterräder"],
    notes:
      "Familienauto, das uns eine Nummer zu gross geworden ist. Suche einen Kombi mit Anhängerkupplung.",
    serviceHistory: "lückenlos scheckheft",
    previousOwners: 1,
    accidentFree: true,
    mfkUntil: "2029-09-19",
  },
  {
    id: "v-004",
    make: "Tesla",
    model: "Model Y",
    trim: "Long Range AWD",
    year: 2023,
    firstRegistration: "2023-02-11",
    mileageKm: 68_200,
    fuel: "elektro",
    body: "suv",
    drivetrain: "allrad",
    powerPs: 514,
    listPriceNew: 61_990,
    condition: "gut",
    color: "Midnight Silver",
    rangeKm: 533,
    batterySoh: 91,
    features: ["Panoramadach", "Anhängerkupplung", "Winterräder"],
    notes: "Vielfahrer-Auto, Supercharger-Historie lückenlos. Neue Bremsen im Mai 2026.",
    serviceHistory: "teilweise",
    previousOwners: 1,
    accidentFree: true,
    mfkUntil: "2027-02-11",
  },
  {
    id: "v-005",
    make: "BMW",
    model: "iX3",
    trim: "M Sport",
    year: 2024,
    firstRegistration: "2024-10-05",
    mileageKm: 31_500,
    fuel: "elektro",
    body: "suv",
    drivetrain: "heck",
    powerPs: 286,
    listPriceNew: 72_300,
    condition: "sehr gut",
    color: "Carbonschwarz",
    rangeKm: 460,
    batterySoh: 95,
    features: ["Head-up-Display", "Harman Kardon", "Panoramadach", "Matrix-LED", "Anhängerkupplung"],
    notes: "Leasingrückläufer aus Erstbesitz. Ich will zurück zum Verbrenner für die Alpenpässe.",
    serviceHistory: "lückenlos scheckheft",
    previousOwners: 1,
    accidentFree: true,
    mfkUntil: "2028-10-05",
  },
  {
    id: "v-006",
    make: "Audi",
    model: "Q4 e-tron",
    trim: "50 quattro S line",
    year: 2023,
    firstRegistration: "2023-07-21",
    mileageKm: 52_900,
    fuel: "elektro",
    body: "suv",
    drivetrain: "allrad",
    powerPs: 299,
    listPriceNew: 66_800,
    condition: "gut",
    color: "Navarrablau",
    rangeKm: 488,
    batterySoh: 93,
    features: ["Matrix-LED", "Sportfahrwerk", "360°-Kamera", "Winterräder"],
    defects: ["Steinschlag Frontscheibe, reparaturfähig"],
    serviceHistory: "lückenlos scheckheft",
    previousOwners: 2,
    accidentFree: true,
    mfkUntil: "2027-07-21",
  },
  {
    id: "v-007",
    make: "VW",
    model: "ID.7 Tourer",
    trim: "Pro S",
    year: 2025,
    firstRegistration: "2025-01-30",
    mileageKm: 38_100,
    fuel: "elektro",
    body: "kombi",
    drivetrain: "heck",
    powerPs: 286,
    listPriceNew: 63_500,
    condition: "sehr gut",
    color: "Kings Red",
    rangeKm: 685,
    batterySoh: 96,
    features: ["Anhängerkupplung", "Wärmepumpe", "Head-up-Display", "Massagesitze", "Panoramadach"],
    notes:
      "Der beste Langstrecken-Kombi, den ich je hatte — aber ich brauche jetzt einen SUV mit Allrad fürs Berggebiet.",
    serviceHistory: "lückenlos scheckheft",
    previousOwners: 1,
    accidentFree: true,
    mfkUntil: "2029-01-30",
  },
  {
    id: "v-008",
    make: "Porsche",
    model: "Macan",
    trim: "GTS",
    year: 2022,
    firstRegistration: "2022-05-17",
    mileageKm: 44_600,
    fuel: "benzin",
    body: "suv",
    drivetrain: "allrad",
    powerPs: 440,
    listPriceNew: 118_400,
    condition: "sehr gut",
    color: "Kreide",
    features: ["Luftfederung", "Sportfahrwerk", "Bowers & Wilkins", "Panoramadach", "Winterräder", "AHK abnehmbar"],
    notes:
      "Ungern, aber der Verbrauch in der Stadt geht nicht mehr. Suche einen souveränen Stromer mit Ladeleistung.",
    serviceHistory: "lückenlos scheckheft",
    previousOwners: 1,
    accidentFree: true,
    mfkUntil: "2027-05-17",
  },
  {
    id: "v-009",
    make: "Volvo",
    model: "XC60",
    trim: "T6 Recharge AWD",
    year: 2023,
    firstRegistration: "2023-11-09",
    mileageKm: 41_200,
    fuel: "hybrid",
    body: "suv",
    drivetrain: "allrad",
    powerPs: 350,
    listPriceNew: 79_600,
    condition: "sehr gut",
    color: "Denim Blue",
    rangeKm: 78,
    features: ["Anhängerkupplung", "Harman Kardon", "Panoramadach", "Pilot Assist", "Winterräder"],
    serviceHistory: "lückenlos scheckheft",
    previousOwners: 1,
    accidentFree: true,
    mfkUntil: "2027-11-09",
  },
  {
    id: "v-010",
    make: "Kia",
    model: "EV6",
    trim: "GT-Line AWD",
    year: 2023,
    firstRegistration: "2023-04-26",
    mileageKm: 58_700,
    fuel: "elektro",
    body: "kompakt",
    drivetrain: "allrad",
    powerPs: 325,
    listPriceNew: 58_900,
    condition: "gut",
    color: "Yacht Blue",
    rangeKm: 506,
    batterySoh: 92,
    features: ["Wärmepumpe", "Head-up-Display", "360°-Kamera", "Winterräder"],
    serviceHistory: "lückenlos scheckheft",
    previousOwners: 1,
    accidentFree: true,
    mfkUntil: "2027-04-26",
  },
  {
    id: "v-011",
    make: "Hyundai",
    model: "Ioniq 5",
    trim: "N",
    year: 2024,
    firstRegistration: "2024-03-12",
    mileageKm: 24_800,
    fuel: "elektro",
    body: "kompakt",
    drivetrain: "allrad",
    powerPs: 650,
    listPriceNew: 76_500,
    condition: "sehr gut",
    color: "Performance Blue",
    rangeKm: 448,
    batterySoh: 94,
    features: ["Sportfahrwerk", "Bowers & Wilkins", "Head-up-Display", "Winterräder"],
    notes: "Trackday-Auto, aber nie im Renneinsatz. Bremsen und Reifen frisch.",
    serviceHistory: "lückenlos scheckheft",
    previousOwners: 1,
    accidentFree: true,
    mfkUntil: "2028-03-12",
  },
  {
    id: "v-012",
    make: "Mercedes-Benz",
    model: "EQE SUV",
    trim: "350 4MATIC",
    year: 2024,
    firstRegistration: "2024-01-19",
    mileageKm: 47_300,
    fuel: "elektro",
    body: "suv",
    drivetrain: "allrad",
    powerPs: 292,
    listPriceNew: 94_700,
    condition: "gut",
    color: "Obsidianschwarz",
    rangeKm: 552,
    batterySoh: 93,
    features: ["Luftfederung", "Massagesitze", "Burmester", "Panoramadach", "Head-up-Display", "360°-Kamera"],
    serviceHistory: "lückenlos scheckheft",
    previousOwners: 2,
    accidentFree: false,
    mfkUntil: "2028-01-19",
  },
  {
    id: "v-013",
    make: "Toyota",
    model: "RAV4",
    trim: "2.5 Hybrid AWD-i Premium",
    year: 2022,
    firstRegistration: "2022-08-30",
    mileageKm: 71_400,
    fuel: "hybrid",
    body: "suv",
    drivetrain: "allrad",
    powerPs: 222,
    listPriceNew: 52_300,
    condition: "gut",
    color: "Dynamic Grey",
    features: ["Anhängerkupplung", "Winterräder", "360°-Kamera"],
    serviceHistory: "lückenlos scheckheft",
    previousOwners: 1,
    accidentFree: true,
    mfkUntil: "2027-08-30",
  },
  {
    id: "v-014",
    make: "Cupra",
    model: "Formentor",
    trim: "VZ 2.0 TSI 4Drive",
    year: 2023,
    firstRegistration: "2023-06-07",
    mileageKm: 49_900,
    fuel: "benzin",
    body: "kompakt",
    drivetrain: "allrad",
    powerPs: 310,
    listPriceNew: 56_400,
    condition: "sehr gut",
    color: "Petrol Blue",
    features: ["Sportfahrwerk", "Matrix-LED", "Panoramadach", "Winterräder"],
    serviceHistory: "teilweise",
    previousOwners: 1,
    accidentFree: true,
    mfkUntil: "2027-06-07",
  },
  {
    id: "v-015",
    make: "BMW",
    model: "i4",
    trim: "M50 xDrive",
    year: 2023,
    firstRegistration: "2023-09-14",
    mileageKm: 55_100,
    fuel: "elektro",
    body: "limousine",
    drivetrain: "allrad",
    powerPs: 544,
    listPriceNew: 81_200,
    condition: "gut",
    color: "Frozen Portimao",
    rangeKm: 510,
    batterySoh: 92,
    features: ["Head-up-Display", "Harman Kardon", "Sportfahrwerk", "Matrix-LED"],
    serviceHistory: "lückenlos scheckheft",
    previousOwners: 1,
    accidentFree: true,
    mfkUntil: "2027-09-14",
  },
  {
    id: "v-016",
    make: "Skoda",
    model: "Enyaq",
    trim: "85x Sportline",
    year: 2025,
    firstRegistration: "2025-02-24",
    mileageKm: 26_600,
    fuel: "elektro",
    body: "suv",
    drivetrain: "allrad",
    powerPs: 286,
    listPriceNew: 59_800,
    condition: "sehr gut",
    color: "Velvet Red",
    rangeKm: 545,
    batterySoh: 97,
    features: ["Anhängerkupplung", "Wärmepumpe", "Panoramadach", "Winterräder", "360°-Kamera"],
    serviceHistory: "lückenlos scheckheft",
    previousOwners: 1,
    accidentFree: true,
    mfkUntil: "2029-02-24",
  },
  {
    id: "v-017",
    make: "Polestar",
    model: "2",
    trim: "Long Range Dual Motor",
    year: 2023,
    firstRegistration: "2023-03-18",
    mileageKm: 62_400,
    fuel: "elektro",
    body: "limousine",
    drivetrain: "allrad",
    powerPs: 421,
    listPriceNew: 62_700,
    condition: "gut",
    color: "Thunder",
    rangeKm: 592,
    batterySoh: 93,
    features: ["Harman Kardon", "Pilot Assist", "Wärmepumpe", "Winterräder"],
    serviceHistory: "lückenlos scheckheft",
    previousOwners: 2,
    accidentFree: true,
    mfkUntil: "2027-03-18",
  },
  {
    id: "v-018",
    make: "Volvo",
    model: "V90",
    trim: "B5 AWD Cross Country",
    year: 2022,
    firstRegistration: "2022-11-11",
    mileageKm: 83_500,
    fuel: "hybrid",
    body: "kombi",
    drivetrain: "allrad",
    powerPs: 250,
    listPriceNew: 74_900,
    condition: "gut",
    color: "Pine Grey",
    features: ["Anhängerkupplung", "Luftfederung", "Panoramadach", "Standheizung", "Winterräder"],
    serviceHistory: "lückenlos scheckheft",
    previousOwners: 2,
    accidentFree: true,
    mfkUntil: "2027-11-11",
  },
];

/**
 * Inserate. Jedes Inserat verknüpft ein Fahrzeug mit dem Tauschwunsch seines
 * Besitzers — genau daraus entsteht das Matching.
 */
export const seedListings: SeedListing[] = [
  {
    id: "l-001",
    vehicleId: "v-001",
    ownerId: "u-001",
    createdAt: "2026-08-20",
    wish: {
      makes: ["Zeekr", "BMW", "Skoda", "VW"],
      bodies: ["suv"],
      fuels: ["elektro"],
      minYear: 2024,
      maxCashOut: 9_000,
      notes: "Suche etwas mit schnellerem Laden.",
    },
    views: 233,
  },
  {
    id: "l-019",
    vehicleId: "v-019",
    ownerId: "u-001",
    createdAt: "2026-08-22",
    wish: {
      makes: ["Toyota", "VW", "Skoda"],
      bodies: ["kombi", "suv"],
      fuels: ["hybrid", "benzin"],
      minYear: 2020,
      maxCashOut: 8_000,
    },
    views: 71,
  },
  {
    id: "l-002",
    vehicleId: "v-002",
    ownerId: "u-002",
    createdAt: "2026-08-12",
    wish: {
      makes: ["Polestar", "BMW", "Mercedes-Benz", "Tesla", "VW"],
      bodies: ["suv", "limousine", "kombi"],
      fuels: ["elektro"],
      minYear: 2023,
      maxMileageKm: 60_000,
      maxCashOut: 6_000,
      notes: "Reichweite ab 500 km WLTP ist mir wichtig. Allrad wäre schön, kein Muss.",
    },
    askPremium: 0,
    views: 412,
  },
  {
    id: "l-003",
    vehicleId: "v-003",
    ownerId: "u-006",
    createdAt: "2026-08-25",
    wish: {
      makes: ["Skoda", "VW", "Volvo", "Audi"],
      bodies: ["kombi"],
      fuels: ["elektro", "diesel", "hybrid"],
      minYear: 2020,
      maxMileageKm: 120_000,
      maxCashOut: -8_000,
      notes: "Muss eine Anhängerkupplung haben, sonst bin ich flexibel.",
    },
    askPremium: 500,
    views: 197,
  },
  {
    id: "l-004",
    vehicleId: "v-004",
    ownerId: "u-003",
    createdAt: "2026-07-30",
    wish: {
      makes: ["Polestar", "Zeekr", "Kia", "Hyundai", "Skoda"],
      bodies: ["suv", "kompakt"],
      fuels: ["elektro"],
      minYear: 2024,
      maxCashOut: 15_000,
      notes: "Ich will neuere Software und schnelleres Laden. Zahle die Differenz.",
    },
    views: 288,
  },
  {
    id: "l-005",
    vehicleId: "v-005",
    ownerId: "u-004",
    createdAt: "2026-08-19",
    wish: {
      makes: ["Porsche", "Cupra", "Toyota", "Volvo"],
      bodies: ["suv", "kompakt"],
      fuels: ["benzin", "hybrid"],
      minYear: 2021,
      maxCashOut: 25_000,
    },
    views: 156,
  },
  {
    id: "l-006",
    vehicleId: "v-006",
    ownerId: "u-005",
    createdAt: "2026-08-28",
    wish: {
      makes: ["VW", "Skoda", "Toyota", "Kia"],
      bodies: ["kombi", "suv"],
      fuels: ["elektro", "hybrid"],
      minYear: 2022,
      maxCashOut: 12_000,
    },
    views: 94,
  },
  {
    id: "l-007",
    vehicleId: "v-007",
    ownerId: "u-007",
    createdAt: "2026-08-02",
    wish: {
      makes: ["Zeekr", "Polestar", "Skoda", "Audi", "BMW"],
      bodies: ["suv"],
      fuels: ["elektro"],
      minYear: 2024,
      maxMileageKm: 50_000,
      maxCashOut: 9_000,
      notes: "Allrad ist Bedingung, wir wohnen auf 1'200 m.",
    },
    views: 331,
  },
  {
    id: "l-008",
    vehicleId: "v-008",
    ownerId: "u-009",
    createdAt: "2026-06-15",
    wish: {
      makes: ["Polestar", "Tesla", "BMW", "Mercedes-Benz", "Hyundai", "Zeekr"],
      bodies: ["suv", "limousine"],
      fuels: ["elektro"],
      minYear: 2024,
      maxCashOut: -20_000,
      notes: "Mein Macan ist mehr wert, ich erwarte einen deutlichen Ausgleich.",
    },
    askPremium: 1_500,
    views: 523,
  },
  {
    id: "l-009",
    vehicleId: "v-009",
    ownerId: "u-008",
    createdAt: "2026-08-21",
    wish: {
      makes: ["Toyota", "Skoda", "VW", "Kia"],
      bodies: ["suv", "kombi"],
      fuels: ["hybrid", "diesel", "benzin"],
      minYear: 2021,
      maxCashOut: -12_000,
    },
    views: 143,
  },
  {
    id: "l-010",
    vehicleId: "v-010",
    ownerId: "u-010",
    createdAt: "2026-08-30",
    wish: {
      makes: ["Cupra", "VW", "BMW", "Audi"],
      bodies: ["kompakt", "limousine"],
      fuels: ["benzin", "elektro"],
      minYear: 2022,
      maxCashOut: 8_000,
    },
    views: 76,
  },
  {
    id: "l-011",
    vehicleId: "v-011",
    ownerId: "u-003",
    createdAt: "2026-08-08",
    wish: {
      makes: ["Porsche", "BMW", "Polestar", "Zeekr"],
      bodies: ["suv", "coupe", "limousine"],
      fuels: ["elektro", "benzin"],
      minYear: 2022,
      maxCashOut: 20_000,
    },
    views: 264,
  },
  {
    id: "l-012",
    vehicleId: "v-012",
    ownerId: "u-004",
    createdAt: "2026-07-11",
    wish: {
      makes: ["Polestar", "Volvo", "Zeekr", "BMW"],
      bodies: ["suv", "kombi"],
      fuels: ["elektro", "hybrid"],
      minYear: 2023,
      maxCashOut: -5_000,
    },
    views: 209,
  },
  {
    id: "l-013",
    vehicleId: "v-013",
    ownerId: "u-005",
    createdAt: "2026-08-16",
    wish: {
      makes: ["Skoda", "VW", "Volvo"],
      bodies: ["kombi"],
      fuels: ["diesel", "hybrid"],
      minYear: 2019,
      maxCashOut: -9_000,
      notes: "Mein RAV4 ist mehr wert, ich erwarte einen entsprechenden Ausgleich.",
    },
    views: 61,
  },
  {
    id: "l-014",
    vehicleId: "v-014",
    ownerId: "u-006",
    createdAt: "2026-08-27",
    wish: {
      makes: ["Kia", "Hyundai", "Tesla", "Polestar"],
      bodies: ["kompakt", "suv"],
      fuels: ["elektro"],
      minYear: 2022,
      maxCashOut: 10_000,
    },
    views: 118,
  },
  {
    id: "l-015",
    vehicleId: "v-015",
    ownerId: "u-007",
    createdAt: "2026-08-05",
    wish: {
      makes: ["Zeekr", "Polestar", "Audi", "Mercedes-Benz"],
      bodies: ["suv"],
      fuels: ["elektro"],
      minYear: 2024,
      maxCashOut: 12_000,
    },
    views: 187,
  },
  {
    id: "l-016",
    vehicleId: "v-016",
    ownerId: "u-009",
    createdAt: "2026-08-23",
    wish: {
      makes: ["Polestar", "Tesla", "BMW", "Zeekr"],
      bodies: ["suv", "limousine"],
      fuels: ["elektro"],
      minYear: 2023,
      maxCashOut: 14_000,
    },
    views: 132,
  },
  {
    id: "l-017",
    vehicleId: "v-017",
    ownerId: "u-010",
    createdAt: "2026-08-14",
    wish: {
      makes: ["Skoda", "VW", "Toyota", "Volvo"],
      bodies: ["kombi", "suv"],
      fuels: ["diesel", "hybrid", "benzin"],
      minYear: 2020,
      maxCashOut: 2_000,
    },
    views: 88,
  },
  {
    id: "l-018",
    vehicleId: "v-018",
    ownerId: "u-008",
    createdAt: "2026-08-18",
    wish: {
      makes: ["Zeekr", "Polestar", "Skoda", "VW"],
      bodies: ["suv", "kombi"],
      fuels: ["elektro"],
      minYear: 2024,
      maxCashOut: 6_000,
      notes: "Anhängerkupplung wird gebraucht, wir ziehen einen Wohnwagen.",
    },
    views: 174,
  },
];
